name: covid
description: Covid-19 Update


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  cuberto_bottom_bar: ^1.1.1+1
  flag: ^2.0.1
  percent_indicator: ^2.1.3
  animations: ^1.0.0+5
  http: ^0.12.1
  bloc:
  flutter_bloc:
  equatable:
  flutter_money_formatter: ^0.8.3
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.4.7
  route_transitions: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name :
  name : "Covid-19 Update"



flutter:


  uses-material-design: true


  assets:
    - src/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: src/font/MontserratAlternates-Regular.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: src/font/MontserratAlternates-SemiBold.ttf
    - family: Montserrat Bold
      fonts:
        - asset: src/font/Montserrat-Bold.ttf
    - family: Poppins Bold
      fonts:
        - asset: src/font/Poppins-Bold.ttf
    - family: Popping SemiBold
      fonts:
        - asset: src/font/Poppins-SemiBold.ttf
    - family: Popping SemiBold
      fonts:
        - asset: src/font/CustomIcons.ttf

